### GET request for actuator endpoints

GET http://localhost:8080/actuator
Authorization: Basic user secret
###

GET http://localhost:8080/actuator
Authorization: Basic admin admin
###

GET http://localhost:8080/actuator/health
###

GET http://localhost:8080/actuator/env
Authorization: Basic admin admin
###

GET http://localhost:8080/actuator/info
Authorization: Basic admin admin
###

GET http://localhost:8080/actuator/metrics/http.server.requests
Authorization: Basic admin admin
###

GET http://localhost:8080/actuator/sbom/application
Authorization: Basic admin admin
###