### GET request for message endpoint

GET http://localhost:8080/api/private/message
Authorization: Basic {{standard_user_name}} {{standard_user_pwd}}
###

GET http://localhost:8080/api/public/message
###